---
apiVersion: v1
kind: Service
metadata:
  name: comet-service
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: kube-system-skipverify@kubernetescrd
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: comet-service
subsets:
  - addresses:
      - ip: 10.38.16.207
    ports:
      - port: 443
