apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ha-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ha.vexdev.com`)
      kind: Rule
      services:
        - name: ha-external-service
          kind: Service
          port: 80  # Internal service port (ClusterIP service will handle forwarding)
  tls:
    certResolver: letsencrypt-prod
