apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ha-tls-ingress
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  rules:
    - host: ha.vexdev.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ha-service
                port:
                  number: 8123
  tls:
    - secretName: ha-tls
      hosts:
        - ha.vexdev.com