---
apiVersion: v1
kind: Service
metadata:
  name: ha-external-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80       # Internal service port (Traefik forwards here)
      targetPort: 8123  # Target external service port
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ha-external-service
subsets:
  - addresses:
      - ip: 10.38.16.24  # External IP
    ports:
      - port: 8123  # External service port
