apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxmox-tls-ingress
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  rules:
    - host: proxmox.vexdev.com
      https:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxmox-service
                port:
                  number: 8006
  tls:
    - secretName: proxmox-tls
      hosts:
        - proxmox.vexdev.com