apiVersion: v1
kind: Service
metadata:
  name: proxmox-service
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: skipverify@kubernetescrd
spec:
  type: ExternalName
  externalName: 10.38.16.2