---
apiVersion: v1
kind: Service
metadata:
  name: proxmox-service
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: skipverify@kubernetescrd
spec:
  type: ClusterIP  # Can also be NodePort or LoadBalancer
  ports:
    - protocol: TCP
      port: 8006  # Internal cluster port
      targetPort: 8006  # External service port
---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox-service
subsets:
  - addresses:
      - ip: 10.38.16.2 
    ports:
      - port: 8006  # External service port
