---
apiVersion: v1
kind: Service
metadata:
  name: router-service
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: kube-system-skipverify@kubernetescrd
spec:
  type: ClusterIP  # Can also be NodePort or LoadBalancer
  ports:
    - protocol: TCP
      port: 4443  # Internal cluster port
      targetPort: 4443  # External service port
---
apiVersion: v1
kind: Endpoints
metadata:
  name: router-service
subsets:
  - addresses:
      - ip: 10.38.16.1
    ports:
      - port: 4443  # External service port
