apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: router-tls-ingress
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd,default-only-local-middleware@kubernetescrd
spec:
  rules:
    - host: router.vexdev.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: router-service
                port:
                  number: 4443
  tls:
    - secretName: router-tls
      hosts:
        - router.vexdev.com