apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-homes-volume-claim
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-nas-homes
  resources:
    requests:
      storage: 2Ti
