apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: authentik-secret-envs
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  itemPath: "vaults/kubernetes/items/authentik-secret-envs"