apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: audiobookshelf
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/vexdev/vex-k8s.git
    path: charts/audiobookshelf
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: audiobookshelf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
