apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/vexdev/vex-k8s.git
    path: charts/paperless
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: paperless
  ignoreDifferences:
    - jsonPointers:
        - /data
      kind: Secret
      name: paperless-redis
    - group: apps
      jsonPointers:
        - /spec/template/metadata/annotations
      kind: StatefulSet
      name: paperless-redis-master
      namespace: paperless
    - group: apps
      jsonPointers:
        - /spec/template/metadata/annotations
      kind: StatefulSet
      name: paperless-redis-replicas
      namespace: paperless
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
