apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: photos-volume-provisioner
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    chart: nfs-subdir-external-provisioner
    targetRevision: 4.0.18
    helm:
      valuesObject:
        nfs:
          server: 10.38.16.20
          path: /volume1/photo
        storageClass:
          name: nfs-photo
          reclaimPolicy: Retain  # Prevents auto-deletion of data when PVC is removed
          pathPattern: "${.PVC.name}"  # Ensures predictable directory names
          archiveOnDelete: false  # Prevents the provisioner from archiving folders
          onDelete: retain  # Explicitly retains folders when PVC is deleted
        nodeSelector:
          kubernetes.io/hostname: k8s-node-vex
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
