apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tolgee
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/throrin19/helm-tolgee.git
    path: charts/tolgee
    targetRevision: 47c9f823904f30b207bdaf841d97c7079b2f7747
    helm:
      values: |
        image.tag: 3.120.0
        ingress.enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: tolgee
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true