# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json
common:
  defaultPodOptions:
    nodeSelector:
      vex.location: swisshome
  controllers:
    main:
      strategy: Recreate
      containers:
        main:
          image:
            repository: ghcr.io/advplyr/audiobookshelf
            tag: 2.19.5
            pullPolicy: IfNotPresent
          env:
            TZ: Europe/Zurich

  service:
    main:
      controller: main
      ports:
        http:
          port: 80
  ingress:
    main:
      enabled: true
      hosts:
        - host: library.vexdev.com
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      annotations:
        spec.ingressClassName: traefik
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/service.serversscheme: http
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd,default-default-headers@kubernetescrd
      tls:
        - secretName: audiobookshelf-tls
          hosts:
            - library.vexdev.com

  # -- Configure persistence settings for the chart under this key.
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /config
    metadata:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /metadata
    audiobooks:
      enabled: true
      storageClass: nfs-abs-audiobooks
      accessMode: ReadWriteOnce
      size: 8Gi
    backup:
      enabled: true
      storageClass: nfs-abs-backup
      accessMode: ReadWriteOnce
      size: 1Gi
    books:
      enabled: true
      storageClass: nfs-abs-books
      accessMode: ReadWriteOnce
      size: 2Gi

nfs1:
  nfs:
    server: 10.38.16.20
    path: /volume1/audiobooks
  storageClass:
    name: nfs-abs-audiobooks
    reclaimPolicy: Retain # Prevents auto-deletion of data when PVC is removed
    pathPattern: "/" # Use the root of the NFS share
    archiveOnDelete: false # Prevents the provisioner from archiving folders
    onDelete: retain # Explicitly retains folders when PVC is deleted
  nodeSelector:
    vex.location: swisshome

nfs2:
  nfs:
    server: 10.38.16.20
    path: /volume1/backup
  storageClass:
    name: nfs-abs-backup
    reclaimPolicy: Retain # Prevents auto-deletion of data when PVC is removed
    pathPattern: "/" # Use the root of the NFS share
    archiveOnDelete: false # Prevents the provisioner from archiving folders
    onDelete: retain # Explicitly retains folders when PVC is deleted
  nodeSelector:
    vex.location: swisshome

nfs3:
  nfs:
    server: 10.38.16.20
    path: /volume1/books
  storageClass:
    name: nfs-abs-books
    reclaimPolicy: Retain # Prevents auto-deletion of data when PVC is removed
    pathPattern: "/" # Use the root of the NFS share
    archiveOnDelete: false # Prevents the provisioner from archiving folders
    onDelete: retain # Explicitly retains folders when PVC is deleted
  nodeSelector:
    vex.location: swisshome
