apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tolgee-tls-ingress
  namespace: tolgee
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/service.serverScheme: http  # Ensure HTTP backend
    traefik.ingress.kubernetes.io/router.middlewares: default-default-headers@kubernetescrd,default-redirect-https@kubernetescrd,default-authentik@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: tolgee.vexdev.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tolgee
                port:
                  number: 8080
  tls:
    - hosts:
        - tolgee.vexdev.com
      secretName: tolgee-tls
