k8s-monitoring:
  cluster:
    name: vex-k8s

  destinations:
    - name: hostedMetrics
      type: prometheus
      url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
      auth:
        type: basic
        usernameKey: GRAFANA_CLOUD_PROMETHEUS_USERNAME
        passwordKey: GRAFANA_CLOUD_PROMETHEUS_PASSWORD
      secret:
        create: false
        name: grafana-cloud-secret-envs
        namespace: monitoring
    - name: hostedLogs
      type: loki
      url: https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push
      auth:
        type: basic
        usernameKey: GRAFANA_CLOUD_LOKI_USERNAME
        passwordKey: GRAFANA_CLOUD_LOKI_PASSWORD
      secret:
        create: false
        name: grafana-cloud-secret-envs
        namespace: monitoring

  # Features to enable, which determines what data to collect
  clusterMetrics:
    enabled: true
    opencost:
      enabled: false
    kepler:
      enabled: false
  clusterEvents:
    enabled: true
  podLogs:
    enabled: true
  alloy-logs:
    enabled: true
  alloy-metrics:
    enabled: true
  alloy-singleton:
    enabled: true