apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: root-ingress
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  rules:
    - host: vexdev.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: assets-nginx
                port:
                  name: http
  tls:
    - secretName: vexdev.com-tls
      hosts:
        - vexdev.com