nginx:
  staticSitePVC: nfs-assets
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hostname: assets.vexdev.com
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/service.serversscheme: http
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd,default-default-headers@kubernetescrd
    tls: true
  serverBlock: |-
    server {
        listen  8080;

        location ~ /\.(?!well-known).* {
            deny all;
            access_log off;
            log_not_found off;
        }
        location /status {
            stub_status on;
            access_log   off;
            allow 127.0.0.1;
            deny all;
        }
        location /topo.zip {
            resolver 8.8.8.8 ipv6=off;
            set $backend "https://data.geo.admin.ch";
            proxy_pass $backend/ch.swisstopo.amtliches-gebaeudeadressverzeichnis/amtliches-gebaeudeadressverzeichnis_ch/amtliches-gebaeudeadressverzeichnis_ch_2056.csv.zip;
            proxy_set_header Host www.google.com;
            proxy_redirect off;
        }
    }

nfs:
  nfs:
    server: 100.91.224.51
    path: /volume1/nfs-assets
  storageClass:
    name: nfs-assets
    reclaimPolicy: Retain # Prevents auto-deletion of data when PVC is removed
    pathPattern: "/" # Use the root of the NFS share
    archiveOnDelete: false # Prevents the provisioner from archiving folders
    onDelete: retain # Explicitly retains folders when PVC is deleted
  nodeSelector:
    vex.location: swisshome
