apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-cd-tls-ingress
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  rules:
    - host: argo.vexdev.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argo-cd
                port:
                  number: 443
  tls:
    - secretName: argo-cd-tls
      hosts:
        - argo.vexdev.com
